#!/usr/bin/env python3
"""Generate test report from output files"""

import sys
from pathlib import Path
import json

def generate_report():
    """Generate markdown report from test outputs"""
    output_dir = Path("output")
    
    print("# OS Development Test Report\n")
    
    # Check for test results
    serial_files = list(output_dir.glob("serial_*.txt"))
    
    if serial_files:
        print("## Serial Output\n")
        for f in sorted(serial_files):
            print(f"### {f.stem}\n")
            print("```")
            try:
                content = f.read_text(errors='replace')
                print(content[:500])  # First 500 chars
                if len(content) > 500:
                    print("...")
            except:
                print("[Error reading file]")
            print("```\n")
    
    # Check for QEMU debug log
    qemu_log = output_dir / "qemu_debug.log"
    if qemu_log.exists():
        print("## QEMU Debug Log\n")
        print("```")
        try:
            content = qemu_log.read_text(errors='replace')
            # Show last 20 lines
            lines = content.strip().split('\n')
            for line in lines[-20:]:
                print(line)
        except:
            print("[Error reading QEMU log]")
        print("```\n")
    
    # Summary
    print("## Summary\n")
    print(f"- Serial outputs captured: {len(serial_files)}")
    print(f"- QEMU log available: {qemu_log.exists()}")
    print("\n---")
    print("*Generated by automated test system*")

if __name__ == "__main__":
    generate_report()