name: OS Development Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/os-dev.yml'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-x86 nasm gcc-multilib
        pip install pytest pytest-timeout
    
    - name: Build Bootloader
      run: |
        cd src/boot
        make clean
        make
        ls -la *.bin
    
    - name: Run QEMU Tests
      timeout-minutes: 5
      run: |
        cd tests
        python -m pytest -v --tb=short --capture=no
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          tests/output/*.log
          tests/output/*.bin
          tests/output/*.txt
          qemu.log
    
    - name: Upload Serial Output
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: serial-output
        path: tests/output/serial_*.txt
    
    - name: Generate Test Report
      if: always()
      run: |
        cd tests
        python generate_report.py > ../test_report.md
        cat ../test_report.md
    
    - name: Comment PR with Results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('test_report.md', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: report
          });
